# Titanic Wrangling

In this practice activity you'll continue to work with the titanic dataset in ways that flex what you've learned about both data wrangling and data visualization.


```{python}
pip install pandas
```

```{python}
import numpy as np
import pandas as pd
from plotnine import *
```

```{python}
# Import the titanic dataset here
data_dir = "https://dlsun.github.io/pods/data/"
df_titanic = pd.read_csv(data_dir + "titanic.csv")
```

```{python}
df_titanic
```

```{python}
df_titanic.iloc[3]
```

## 1. Filter the data to include passengers only. Calculate the joint distribution (cross-tab) between a passenger's class and where they embarked.


```{python}
# Code here
df_filtered = df_titanic["class"].isin(["1st", "2nd", "3rd"])
df_filtered
```


```{python}
df_filtered = df_titanic[df_filtered]
pd.crosstab(df_filtered["class"], df_filtered["embarked"], normalize='index')
```

## 2. Using the joint distribution that calculated above, calculate the following:

* the conditional distribution of their class given where they embarked
* the conditional distribution of where they embarked given their class

Use the conditional distributions that you calculate to answer the following quesitons:

* What proportion of 3rd class passengers embarked at Southampton?
* What proportion of Southampton passengers were in 3rd class?


```{python}
df_titanic.groupby("class")['embarked'].value_counts(normalize=True)
```


```{python}
#the conditional distribution of their class given where they emabarked
pd.crosstab(df_titanic["class"], df_titanic["embarked"], normalize="columns")
```


```{python}
#the conditional distribution of where they embarked given their class
pd.crosstab(df_titanic["embarked"], df_titanic["class"], normalize="index")
```

What proportion of 3rd class passengers embarked at Southampton?
- 0.305693 of passengers in 3rd class embarked from Southampton.

What proportion of Southampton passengers were in 3rd class?
- 0.696756 of passengers the embarked from Southampton were in 3rd class.

## 3. Make a visualization showing the distribution of a passenger's class, given where they embarked.

Discuss the pros and cons of using this visualization versus the distributions you calculated before, to answer the previous questions.


```{python}
#make a visualization
df_filtered = df_titanic.loc[df_titanic["class"].isin(["1st", "2nd", "3rd"]), :]

(ggplot(df_filtered, aes(x="embarked", fill="class"))
 + geom_bar(position="fill"))

```